#!/usr/bin/env php
<?php
//
// Reset passwords of users by email or ID
//
// @author      Joseph Mastey <joseph.mastey@gmail.com>
// @author      $Author$
// @version     $Id$
// @copyright   Copyright (c) JRM Ventures LLC, 2010-

require_once("lib/base.php"); 
require_once("lib/db.php"); 
init_magento();

switch($server->argc) {
  case 2:
    $user       = $server->argv[1];
    break;
  default:
    print_help();
    break;
}

$customer   = Mage::getModel("customer/customer");
$customer->setWebsiteId(Mage::app()->getStore()->getWebsite()->getId());

if(is_numeric($user)) {
    $customer = $customer->load($user);
} else {
    $customer = $customer->loadByEmail($user);
}

$password = "password";
$customer->changePassword($password);
print "$user's password is now $password\n";

function putdocs() {
    return array(
        "Reset passwords of users by email address or ID",
        "Usage: magento-test-reset-password USER",
    );
}
