#!/usr/bin/env php
<?php
//
// Reset passwords of users by email or ID
//
// @author      Joseph Mastey <joseph.mastey@gmail.com>
// @author      $Author$
// @version     $Id$
// @copyright   Copyright (c) JRM Ventures LLC, 2010-

require_once("lib/base.php"); 
require_once("lib/db.php"); 
init_magento();

switch($_SERVER['argc']) {
  case 2:
    $user       = $_SERVER['argv'][1];
    break;
  default:
    print "Usage: magento-test-reset-password user";
    exit;
}

$customer   = Mage::getModel("customer/customer");
$customer->setWebsiteId(Mage::app()->getStore()->getWebsite()->getId());

if(is_numeric($user)) {
    $customer = $customer->load($user);
} else {
    $customer = $customer->loadByEmail($user);
}

$password = "password";
$customer->changePassword($password);
