#!/usr/bin/env ruby

require 'rubygems'
require 'date'
require 'json'

utils = [
  'magento-jobs-odesk',
  'magento-jobs-elance',
  'magento-jobs-freelancer',
  'magento-jobs-craigslist',
]

#utils = [ 'magento-jobs-freelancer' ]

all_results = []
threads = []
utils.each do |util|
  threads << Thread.new {
    util_name = util.gsub(/magento-jobs-/, '')
    $stderr.puts "Retrieving entries from #{util}\n"
    res_json = `#{util} -j`
    JSON.parse(res_json).each do |row|
      row["util"] = util_name
      all_results << row
    end
  }
end

threads.each { |t| t.join }

(all_results.sort { |l,r| l["date"] <=> r["date"] }).each do |r|
  print "%-12s\t%6s\t%-20s\t%-65s\t%s\n" % [r["util"], r["date"], r["budget"], r["title"], r["link"]]
end
