#!/usr/bin/env php
<?php
//
// Create nonce data to test the system at load.
//
// @author      Joseph Mastey <joseph.mastey@gmail.com>
// @author      $Author$
// @version     $Id$
// @copyright   Copyright (c) JRM Ventures LLC, 2010-

require_once("lib/base.php"); 
require_once("lib/yml.php"); 
require_once("lib/db.php"); 
session_start();
init_magento();

if(2 > $_SERVER['argc']) {
    print_help();
}

// include all fixture libraries
$files = explode("\n", trim(`ls $lib_dir/fixtures`));
foreach($files as $file) {
    require_once("$lib_dir/fixtures/$file");
}

// load requested fixtures
try {
    for($i = 1; $i < $_SERVER['argc']; $i++) {
        $fixture = $_SERVER['argv'][$i];
        print "loading fixture: $fixture\n";
        load_fixture($fixture);
        print "\n";
    }
} catch(Exception $e) {
    print "Fixture import bailed partway through. Likely partial data needs to be expunged.\nException: ".$e->getMessage()."\n";
    print $e->getTraceAsString();
}

function putdocs() {
    return array(
        "Create nonce data to test the system at load.",
        "Usage: magento-test-fixture FIXTURE",
    );
}
