#!/usr/bin/env php
<?php
//
// Output help information
//
// @author 		Joseph Mastey <joseph.mastey@gmail.com>
// @author      $Author$
// @version     $Id$
// @copyright	Copyright (c) JRM Ventures LLC, 2010-

require_once("lib/base.php");

$basedir    = dirname(__FILE__);
$commands   = explode("\n", `ls $basedir | grep magento | sed -e "s/magento-//"`);

if(1 >= $_SERVER['argc']) {
    print "\n";
    readfile("$basedir/README");
    print "\nAvailable commands:\n";
    foreach($commands as $command) {
        print "  $command\n";
    }
    exit;
}
                     
$cmd        = $_SERVER['argv'][1];
if(in_array($cmd, $commands)) {
    passthru("magento-$cmd --help");
} else {
    print "No help found because you're just making up pretend commands. So sad.\n";
}   

function putdocs() {
    return array(
        "Get a list of commands, and information about each command",
        "Usage: magento-help COMMAND",
    );
}
