#!/usr/bin/ruby

require 'rubygems'
require 'hpricot'
require 'open-uri'
require 'date'
require 'optparse'


options = {}
optparse = OptionParser.new(:posix) do |opts|
  opts.banner = "Check major metro areas on Craigslist for Magento related jobs.\nUsage: magento-craigslist-jobs [options]"

  options[:days] = 7
  opts.on( "-d N", "--days=N", Integer, "How recent listings must be (default is #{options[:days]})" ) do |days|
    options[:days] = days
  end

  opts.on( '-h', '--help', 'Display this screen' ) do
    puts opts
    exit
  end
end

begin
  optparse.parse!
rescue OptionParser::ParseError => e
  puts e
  exit
end

today   = Date.today
urlbase = 'http://%s.craigslist.org/search/?areaID=11&subAreaID=&query=magento&catAbb=ggg'
areas   = [ 'newyork', 'chicago', 'sfbay', 'washingtondc.en', 'losangeles',
            'houston', 'denver', 'boston', 'austin', 'atlanta', 'dallas',
            'detroit', 'houston', 'lasvegas', 'miami', 'minneapolis',
            'orangecounty', 'philadelphia', 'phoenix', 'portland', 'raleigh',
            'sacramento', 'sandiego', 'seattle' ]

results = []

areas.each do |area|
  print "#{area}|"

  doc = Hpricot(open(urlbase % area))
  ((doc.search('blockquote')[1]).search("p")).each do |line|
    vals = line.innerHTML.scan(/(.*) - <a href="([^"]*)">([^<]*)<\/a>.*/)

    date = Date.parse(vals[0][0])
    link = vals[0][1]
    title = vals[0][2]

    next if (today - date) > options[:days]
    results << "%6s\t%-60s\t%-10s\t%s\n" % [date.strftime("%m/%d"), link, area, title]
  end
end

puts ""
results.sort.each { |l| puts l }
