#!/usr/bin/env php
<?php
//
// Run some Magento indices
//
// @author      Joseph Mastey <joseph.mastey@gmail.com>
// @author      $Author$
// @version     $Id$
// @copyright   Copyright (c) JRM Ventures LLC, 2010-

require_once("lib/base.php"); 
init_magento();

$indices = array(
    "all" => "Run All Indexes",
    "catalogrule" => "Catalog Price Rules",
);

print "Available indices:\n";
foreach($indices as $key => $selection) {
    printf("%-15s %s\n", $key, $selection);
}

$choice = user_array_choice("\nPick a reindexing action", array_keys($indices));
$choice();

### ACTUAL INDEX RUNNERS ###

function catalogrule() {
    print_error("Running catalogrule index.");
    $observer = Mage::getModel("catalogrule/observer");
    $observer->applyAllRules($observer);
    print_error("Finished with catalogrule index.");
}
