#!/usr/bin/env php
<?php
//
// Clear all test data from the system.
//
// @author      Joseph Mastey <joseph.mastey@gmail.com>
// @author      $Author$
// @version     $Id$
// @copyright   Copyright (c) JRM Ventures LLC, 2010-

require_once("lib/base.php"); 
require_once("lib/db.php"); 

$path   = "dev/debug/template_hints";
$val    = (int)get_config_data($path)? 0 : 1;

print "Turning ".($val?"ON":"OFF")." template hints.\n";
set_config_data($path, $val);
