#!/usr/bin/env php
<?php
//
// Dispatch to other Magento
//
// @author      Joseph Mastey <joseph.mastey@gmail.com>
// @author      $Author$
// @version     $Id$
// @copyright   Copyright (c) JRM Ventures LLC, 2010-

require_once("lib/base.php"); 

if(2 > $server->argc) {
    print_help();
}

$command = $server->argv[1];
array_shift($server->argv);
array_shift($server->argv);
$args = implode(" ", $server->argv);

print `magento-$command $args`;

function putdocs() {
	print_error(`magento-help`);
}
