#!/usr/bin/env php
<?php
//
// Get currently used design.
// It's possible to use multiple designs, but we're most interested in the template theme.
//
// @author      Joseph Mastey <joseph.mastey@gmail.com>
// @author      $Author$
// @version     $Id$
// @copyright   Copyright (c) JRM Ventures LLC, 2010-

$use_default_connection = true;
require_once("lib/db.php");

switch($server->argc) {
  case 3:
    $scope    = $server->argv[1];
    $scope_id = $server->argv[2];
    break;
  case 2:
    $scope    = $server->argv[1]; 
    $scope_id = "%";
    break;
  default:
    $scope  = "default";
    $scope_id = 0;
    break;
}

$sqlst  = "select value from core_config_data where path = 'design/theme/skin' and scope = '$scope' and scope_id like '$scope_id' limit 1";
$res    = mysql_query($sqlst, $db_conn) or die("mysql error: ".mysql_error());

$row    = mysql_fetch_array($res);

if(!$row['value']) {
  $row['value'] = "default";
}

print "{$row['value']}\n";

function putdocs() {
    return array(
        "Return the name of the currently configured theme.",
        "Usage: magento-theme",
        "", "It is possible to have multiple active themes, so we will use",
        "the current skin as a reasonable proxy for this information. Note that",
        "it is also possible to designate seasonal designs, which are not",
        "accounted for by this utility.",
    );
}
