#!/usr/bin/env php
<?php
//
// Get magento version
//
// @author 		Joseph Mastey <joseph.mastey@gmail.com>
// @author    $Author$
// @version   $Id$
// @copyright	Copyright (c) JRM Ventures LLC, 2010-

require_once("lib/base.php"); 
init_magento();

print Mage::getVersion()."\n";
