#!/usr/bin/env php
<?php
//
// Get the list of currently installed modules
//
// @author      Joseph Mastey <joseph.mastey@gmail.com>
// @author      $Author$
// @version     $Id$
// @copyright   Copyright (c) JRM Ventures LLC, 2010-

require_once("lib/base.php");

$simple = false;
if($_SERVER['argc']) {
    $target_code_pool = $_SERVER['argv'][1];
    if(3 == $_SERVER['argc']) {
        $simple = true;
    }
}

$results = `find $magento/app/code/*/* -maxdepth 1 -mindepth 1 -type d | grep -v .svn`;
$results = explode("\n", $results);

$output = array();
foreach($results as $raw_module) {
    if(!strlen($raw_module)) { continue; }

    $raw_module = str_replace("$magento/app/code/", "", $raw_module);
    list($code_pool, $company, $module) = explode("/", $raw_module);

    if(!$code_pool || !$company || !$module) { continue; }

    if(!isset($output[$code_pool])) { $output[$code_pool] = array(); }
    if(!isset($output[$code_pool][$company])) { $output[$code_pool][$company] = array(); }

    $output[$code_pool][$company][] = $module;
}


foreach($output as $code_pool => $companies) {
    if($target_code_pool && 0 !== strpos($code_pool, $target_code_pool)) { continue; }

    if(!$simple) { print "$code_pool:\n"; }
    foreach($companies as $company => $modules) {
        if(!$simple) { print "\t$company:\n"; }

        foreach($modules as $module) {
            if($simple) {
                print strtolower($module)."\n";
            } else {
                print "\t\t$module\n";
            }
        }

    }
}

function putdocs() {
    return array(
        "Display a list of modules in the various codepools of Magento.",
        "Usage: magento-modules [CODEPOOL] [SIMPLE]",
        "","Codepool may be one of [local|core|community]",
        "If simple behavior is enabled, a newline delimited list of modules will be",
        "printed without any headers.",
    );
}
