#!/usr/bin/env php
<?php
//
// Get magento database stats
//
// @author      Joseph Mastey <joseph.mastey@gmail.com>
// @author      $Author$
// @version     $Id$
// @copyright   Copyright (c) JRM Ventures LLC, 2010-

require_once("lib/base.php"); 
require_once("lib/db.php"); 

$schema = $db_config_array['dbname'];
$tables = array(
    "admin_user" => "user_id",
    "catalog_category_entity" => "entity_id",
    "catalog_product_entity" => "entity_id",
    "core_store" => "store_id",
    "customer_entity" => "entity_id",
    "sales_flat_quote" => "entity_id",
    "sales_order" => "entity_id",
    "sales_flat_order" => "entity_id",
    "rating" => "rating_id",
    "review" => "review_id",
);
$sqlst  = "select table_name, table_rows, data_length from information_schema.tables where table_schema = '$schema' and table_name in (\"".implode("\", \"", array_keys($tables))."\")";

$res    = mysql_query($sqlst);
if(!$res) {
    throw new Exception("Failed at life.");
}

$format_string = "%30s\t%10s\t%10s\t%10s\t%10s\n";
printf($format_string, "TABLE", "ROWS", "DATA", "MIN", "MAX");
while($row = mysql_fetch_array($res)) {
    $pk = $tables[$row["table_name"]];
    $sqlst = "select min($pk) min, max($pk) max from {$row['table_name']}";
    $sres = mysql_fetch_array(mysql_query($sqlst));

    $kbytes = $row['data_length']/1024;
    printf($format_string, $row["table_name"], $row["table_rows"], "{$kbytes}k", $sres['min'], $sres['max']);
}

function putdocs() {
    return array(
        "List critical stats from the database.",
        "Usage: magento-stats",
    );
}
