#!/usr/bin/env php
<?php
//
// Display some information about a customer.
//
// @author      Joseph Mastey <joseph.mastey@gmail.com>
// @author      $Author$
// @version     $Id$
// @copyright   Copyright (c) JRM Ventures LLC, 2010-

require_once("lib/base.php");
require_once("lib/db.php");
init_magento();

switch(count($_SERVER['argv'])) {
    case 2:
        $user = $_SERVER['argv'][1];
        break;
    default:
        print_help();
        break;
}

$customer   = Mage::getModel("customer/customer");
$customer->setWebsiteId(Mage::app()->getStore()->getWebsite()->getId());

if(is_numeric($user)) {
    $customer = $customer->load($user);
} else {
    $customer = $customer->loadByEmail($user);
}

print "Customer info for {$customer->getEmail()} (CID {$customer->getId()})\n";


function putdocs() {
    print_error("Usage: magento-customer CUSTOMER\n");
}
