#!/usr/bin/env php
<?php
//
// Get all valid source models for configuration values
//
// @author      Joseph Mastey <joseph.mastey@gmail.com>
// @author      $Author$
// @version     $Id$
// @copyright   Copyright (c) JRM Ventures LLC, 2010-

require_once("lib/base.php");

$command = 'ack "<source_model>" '.$magento.' | awk \'{print $2}\' | grep -v "\-\->" | sed -e "s/.*>\([^<]\+\).*/\1/" | sort | uniq';
print `$command`;

function putdocs() {
    return array(
        "Get a list of source models (lists of selects) available for configuration values",
        "Usage: magento-option-source-models",
    );
}
