#!/bin/bash
#
# Usage: ./permissions.sh [owner.group] [directory_permissions] [file_permissions]
#
# Changes permissions on the magento directory. Meant to be invoked from the
# magento root. Thanks to Igor Rafalovsky for better directory permissions.
#
# @author 		Joseph Mastey <joseph.mastey@gmail.com>
# @author		$Author$
# @version		$Id: permissions.sh 1388 2010-02-12 02:35:36Z joe $
# @copyright	Copyright (c) JRM Ventures LLC, 2009-
#

if [ ! -f "LICENSE.txt" ]; then
	print "This doesn't look like the magento directory. Aborting."
	exit 1
fi

if (( $# > 0 )); then
	owner=$1
	echo "Setting owner on all files to $owner."
	chown -R $owner .
    echo "Done."	
fi

dir_permission='0755'
file_permission='0644'
echo -ne "Is apache the owner of these files (no assumes that it is part of the group)? [Y/n]: "
read DECISION
if [[ "$DECISION" =~ no? ]]; then
    dir_permission='0775'
    file_permission='0664'
fi

echo -ne "Changing directory permissions on all directories to $dir_permission. This may take a while."
find -type d | grep -v .svn | xargs chmod $dir_permission
echo " Done."

echo -ne "Changing file permissions on all files to $file_permission. This may also take a while."
find -type f | grep -v .svn | xargs chmod $file_permission
echo " Done."

echo -ne "Finding and changing .sh files to be executable."
find -type f -name "*.sh" | xargs chmod +x
echo " Done."

echo -ne "Do you want to change media and other directories to allow apache to write to them? [Y/n]: "
read DECISION
if [[ "$DECISION" =~ no? ]]; then
	echo "Skipping media directories. Finished changing permissions."
	exit
fi

# 0777 would be ideal, but PHP on many installations has security problems with files and directories
# running as 0777. this means that we still need to add apache to at least the owner group
# update: actually, stage environment is okay with this, so run with it.
open_dir_permission="0777"
open_file_permission="0666"
echo -ne "Changing permissions on {magento}/var, {magento}/media and {magento}/app/etc to $open_dir_permission to allow writing."
find var -type d | grep -v .svn | xargs chmod $open_dir_permission
find var -type f | grep -v .svn | xargs chmod $open_file_permission
find media -type d | grep -v .svn | xargs chmod $open_dir_permission
find media -type f | grep -v .svn | xargs chmod $open_file_permission
find app/etc -type d | grep -v .svn | xargs chmod $open_dir_permission
find app/etc -type f | grep -v .svn | xargs chmod $open_file_permission
echo " Done."