#!/usr/bin/env php
<?php
//
// Display the layout for an action handle and get details about it
//
// @author    Joseph Mastey <joseph.mastey@gmail.com>
// @author    $Author$
// @version   $Id$
// @copyright Copyright (c) JRM Ventures LLC, 2010-

require_once("lib/base.php"); // load everything
init_magento();

if(2 != $server->argc) {
    print_help();
    exit;
}

$action = $server->argv[1];

$layout = Mage::app()->getLayout();
$front = Mage::app()->getFrontController();
$request = $front->getRequest();
$request->setRequestUri($action);


$request->setPathInfo()->setDispatched(false);
if (!$request->isStraight()) { Mage::getModel('core/url_rewrite')->rewrite(); }
$front->rewrite();

$correctRouter = null;

$i = 0;
while (!$request->isDispatched() && $i++<100) {
    foreach($front->getRouters() as $router) { if ($router->match($request)) { $correctRouter = $router; break; } }
}
if ($i>100) { Mage::throwException('Front controller reached 100 router match iterations'); }

//This event give possibility to launch smth before sending ouptut(Allow cookie setting)
$root = $layout->getBlock('root');
putBlock($root, 'root', "", 0);


function putBlock($block, $alias, $offset = "", $level) {

    $extras = array();
    $extras[] = count($block->getChild()) ? count($block->getChild()) : "-";
    $extras[] = $block->getType();

    // what is rendered?
    if(0 == strcmp($block->getType(), "cms/block")) { $extras[] = $block->getBlockId(); }
    else if(0 == strcmp($block->getType(), "cms/page")) { $extras[] = $block->getPage()->getIdentifier(); }
    else if($block->getTemplate()) { $extras[] = $block->getTemplate(); }
    else { $extras[] = "-"; }

    $extraString = "( ".implode($extras, " | ")." )";

    if($level == 1) { $alias = colorize($alias, C_HI1); }

    echo sprintf("$offset%s %s\n", $alias, colorize($extraString, C_VLO1));

    foreach($block->getChild() as $alias => $childBlock) {
        putBlock($childBlock, $alias, "$offset  ", $level+1);
    }
}

function putdocs() {
    return array(
        "Display information about a controller action's layout.",
        "Usage: magento-layout ACTION",
    );
}
