#!/usr/bin/env php
<?php
//
// Get currently used design.
// It's possible to use multiple designs, but we're most interested in the template theme.
//
// @author      Joseph Mastey <joseph.mastey@gmail.com>
// @author      $Author$
// @version     $Id$
// @copyright   Copyright (c) JRM Ventures LLC, 2010-

require_once("lib/base.php");
require_once("lib/db.php");
init_magento();

var_dump(get_class(Mage::app()->getLayout()->createBlock("Purchase/order_edit")));
