#!/usr/bin/env php
<?php
//
// Get currently used design.
// It's possible to use multiple designs, but we're most interested in the template theme.
//
// @author      Joseph Mastey <joseph.mastey@gmail.com>
// @author      $Author$
// @version     $Id$
// @copyright   Copyright (c) JRM Ventures LLC, 2010-

require_once("lib/base.php");
require_once("lib/db.php");
init_magento();

$collection =  Mage::getModel("enterprise_catalogevent/event")
    ->getCollection()
    ->addFieldToFilter('status', Enterprise_CatalogEvent_Model_Event::STATUS_OPEN)
    ->addImageData();
    ->setCurPage(1)
    ->setPageSize($limit);

print $collection->getSelect() . "";
